from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from rsa.rsa import rsa

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.isclicked=False
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 760)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainHead = QtWidgets.QLabel(self.centralwidget)
        self.mainHead.setGeometry(QtCore.QRect(110, 10, 581, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mainHead.setFont(font)
        self.mainHead.setAlignment(QtCore.Qt.AlignCenter)
        self.mainHead.setObjectName("mainHead")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(20, 80, 781, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.imageInput = QtWidgets.QLineEdit(self.centralwidget)
        self.imageInput.setGeometry(QtCore.QRect(20, 120, 761, 31))
        self.imageInput.setObjectName("imageInput")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(20, 160, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 260, 391, 381))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.p_show = QtWidgets.QLineEdit(self.groupBox)
        self.p_show.setGeometry(QtCore.QRect(150, 90, 231, 21))
        self.p_show.setObjectName("p_show")
        self.q_show = QtWidgets.QLineEdit(self.groupBox)
        self.q_show.setGeometry(QtCore.QRect(150, 120, 231, 21))
        self.q_show.setObjectName("q_show")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.n_show_1 = QtWidgets.QLineEdit(self.groupBox)
        self.n_show_1.setGeometry(QtCore.QRect(150, 180, 231, 21))
        self.n_show_1.setObjectName("n_show_1")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 210, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.e_show = QtWidgets.QLineEdit(self.groupBox)
        self.e_show.setGeometry(QtCore.QRect(150, 210, 231, 22))
        self.e_show.setObjectName("e_show")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 240, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 270, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.n_show = QtWidgets.QLineEdit(self.groupBox)
        self.n_show.setGeometry(QtCore.QRect(150, 270, 231, 21))
        self.n_show.setObjectName("n_show")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 300, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.d_show = QtWidgets.QLineEdit(self.groupBox)
        self.d_show.setGeometry(QtCore.QRect(150, 300, 231, 22))
        self.d_show.setObjectName("d_show")
        self.encryptBtn = QtWidgets.QPushButton(self.centralwidget)
        self.encryptBtn.setGeometry(QtCore.QRect(20, 220, 361, 31))
        self.encryptBtn.clicked.connect(self.clickEncrypt)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.encryptBtn.setFont(font)
        self.encryptBtn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.encryptBtn.setAutoDefault(False)
        self.encryptBtn.setObjectName("encryptBtn")
        self.decryptBtn = QtWidgets.QPushButton(self.centralwidget)
        self.decryptBtn.setGeometry(QtCore.QRect(420, 220, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.decryptBtn.setFont(font)
        self.decryptBtn.setObjectName("decryptBtn")
        self.decryptBtn.clicked.connect(self.clickDecrypt)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(420, 260, 381, 381))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.outData = QtWidgets.QLabel(self.groupBox_2)
        self.outData.setGeometry(QtCore.QRect(10, 50, 361, 321))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.outData.setFont(font)
        self.outData.setObjectName("outData")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(420, 170, 361, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.clearBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearBtn.setGeometry(QtCore.QRect(260, 650, 291, 51))
        self.clearBtn.clicked.connect(self.clickClear)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clearBtn.setFont(font)
        self.clearBtn.setObjectName("clearBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA String Encryption/ Decryption"))
        self.mainHead.setText(_translate("MainWindow", "RSA String Encryption/ Decryption"))
        self.label1.setText(_translate("MainWindow", "Enter the Text to be encrypted"))
        self.label2.setText(_translate("MainWindow", "Enter Length of Bits of prime numbers (p and q): "))
        self.label.setText(_translate("MainWindow", "Generated Keys"))
        self.label_2.setText(_translate("MainWindow", "Primes Generated:"))
        self.label_3.setText(_translate("MainWindow", "First Prime (p):"))
        self.label_4.setText(_translate("MainWindow", "Second Prime (q):"))
        self.label_5.setText(_translate("MainWindow", "Public Keys:"))
        self.label_6.setText(_translate("MainWindow", "N :"))
        self.label_7.setText(_translate("MainWindow", "E :"))
        self.label_8.setText(_translate("MainWindow", "Private Keys:"))
        self.label_9.setText(_translate("MainWindow", "N :"))
        self.label_10.setText(_translate("MainWindow", "D :"))
        self.encryptBtn.setText(_translate("MainWindow", "Encrypt"))
        self.decryptBtn.setText(_translate("MainWindow", "Decrypt"))
        self.label_12.setText(_translate("MainWindow", "DATA"))
        self.outData.setText(_translate("MainWindow", ""))
        self.clearBtn.setText(_translate("MainWindow", "Clear"))
    
    def clickEncrypt(self):
        nowtext=self.imageInput.text()
        if nowtext=="":
            msg=QMessageBox()
            msg.setWindowTitle("Wrong Input!!")
            msg.setText("input field is empty")
            msg.setIcon(QMessageBox.Critical)
            x=msg.exec_()
            return
        z=self.lineEdit.text()
        if not z.isnumeric():
            msg=QMessageBox()
            msg.setWindowTitle("Wrong Input!!")
            msg.setText("input an integer in length of bits")
            msg.setIcon(QMessageBox.Critical)
            x=msg.exec_()
            return
        z=int(z)
        self.isclicked=True
        self.orsa=rsa(z)
        self.orsa.encryptstring(nowtext)
        self.outData.setText(self.orsa.outstrincrypt)
        self.p_show.setText(str(self.orsa.p))
        self.q_show.setText(str(self.orsa.q))
        self.n_show.setText(str(self.orsa.n))
        self.e_show.setText(str(self.orsa.e))
        self.n_show_1.setText(str(self.orsa.n))
        self.d_show.setText(str(self.orsa.d))
        self.label_12.setText("Encrypted Data")

    def clickDecrypt(self):
        if not self.isclicked:
            msg=QMessageBox()
            msg.setWindowTitle("Error!")
            msg.setText("Text not yet encrypted!")
            msg.setIcon(QMessageBox.Critical)
            x=msg.exec_()
            return
        self.orsa.decryptstring()
        self.label_12.setText("Decrypted Data")
        self.outData.setText(self.orsa.findata)


    def clickClear(self):
        self.isclicked=False
        self.outData.setText("")
        self.imageInput.setText("")
        self.label_12.setText("Data")
        self.lineEdit.setText("")
        self.p_show.setText("")
        self.q_show.setText("")
        self.n_show.setText("")
        self.e_show.setText("")
        self.n_show_1.setText("")
        self.d_show.setText("")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
